language: node_js
node_js:
  - stable
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
after_success: "./deploy.sh"
env:
    global:
        - ENCRYPTION_LABEL: "c5a66b2fe33a"
        - COMMIT_AUTHOR_EMAIL: "publish@roydan.com"